In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
faqs = """
Machine learning is fun and exciting
Deep learning is a subset of machine learning
Natural language processing is a branch of artificial intelligence
Artificial intelligence is the future of technology
"""


tokenizer=Tokenizer()
tokenizer.fit_on_texts([faqs])


# always when you add texts you can add multple so it goes in the form of a list


In [ ]:
tokenizer.word_index

len(tokenizer.word_index)

19

In [ ]:
# we will find out all the sentences present in our dataset

for sentence in faqs.split('\n'):
  print(sentence)
  print(tokenizer.texts_to_sequences([sentence]))


[[]]
Machine learning is fun and exciting
[[4, 2, 1, 8, 9, 10]]
Deep learning is a subset of machine learning
[[11, 2, 1, 5, 12, 3, 4, 2]]
Natural language processing is a branch of artificial intelligence
[[13, 14, 15, 1, 5, 16, 3, 6, 7]]
Artificial intelligence is the future of technology
[[6, 7, 1, 17, 18, 3, 19]]

[[]]


In [ ]:
# pure pure sentences ko numbers mei convert kar diya
# Machine learning is fun and exciting
# [[4, 2, 1, 8, 9, 10]]

# Now we have to make a dataset

input_sequences=[]

for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
  for i in range(1, len(tokenized_sentence)):
    print(tokenized_sentence[:i+1])
    input_sequences.append(tokenized_sentence[:i+1])


[4, 2]
[4, 2, 1]
[4, 2, 1, 8]
[4, 2, 1, 8, 9]
[4, 2, 1, 8, 9, 10]
[11, 2]
[11, 2, 1]
[11, 2, 1, 5]
[11, 2, 1, 5, 12]
[11, 2, 1, 5, 12, 3]
[11, 2, 1, 5, 12, 3, 4]
[11, 2, 1, 5, 12, 3, 4, 2]
[13, 14]
[13, 14, 15]
[13, 14, 15, 1]
[13, 14, 15, 1, 5]
[13, 14, 15, 1, 5, 16]
[13, 14, 15, 1, 5, 16, 3]
[13, 14, 15, 1, 5, 16, 3, 6]
[13, 14, 15, 1, 5, 16, 3, 6, 7]
[6, 7]
[6, 7, 1]
[6, 7, 1, 17]
[6, 7, 1, 17, 18]
[6, 7, 1, 17, 18, 3]
[6, 7, 1, 17, 18, 3, 19]


In [ ]:
max_len = max([len(x) for x in input_sequences])
max_len

9

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen=max_len, padding='pre')
padded_input_sequences

array([[ 0,  0,  0,  0,  0,  0,  0,  4,  2],
       [ 0,  0,  0,  0,  0,  0,  4,  2,  1],
       [ 0,  0,  0,  0,  0,  4,  2,  1,  8],
       [ 0,  0,  0,  0,  4,  2,  1,  8,  9],
       [ 0,  0,  0,  4,  2,  1,  8,  9, 10],
       [ 0,  0,  0,  0,  0,  0,  0, 11,  2],
       [ 0,  0,  0,  0,  0,  0, 11,  2,  1],
       [ 0,  0,  0,  0,  0, 11,  2,  1,  5],
       [ 0,  0,  0,  0, 11,  2,  1,  5, 12],
       [ 0,  0,  0, 11,  2,  1,  5, 12,  3],
       [ 0,  0, 11,  2,  1,  5, 12,  3,  4],
       [ 0, 11,  2,  1,  5, 12,  3,  4,  2],
       [ 0,  0,  0,  0,  0,  0,  0, 13, 14],
       [ 0,  0,  0,  0,  0,  0, 13, 14, 15],
       [ 0,  0,  0,  0,  0, 13, 14, 15,  1],
       [ 0,  0,  0,  0, 13, 14, 15,  1,  5],
       [ 0,  0,  0, 13, 14, 15,  1,  5, 16],
       [ 0,  0, 13, 14, 15,  1,  5, 16,  3],
       [ 0, 13, 14, 15,  1,  5, 16,  3,  6],
       [13, 14, 15,  1,  5, 16,  3,  6,  7],
       [ 0,  0,  0,  0,  0,  0,  0,  6,  7],
       [ 0,  0,  0,  0,  0,  0,  6,  7,  1],
       [ 0

In [ ]:
padded_input_sequences

array([[ 0,  0,  0,  0,  0,  0,  0,  4,  2],
       [ 0,  0,  0,  0,  0,  0,  4,  2,  1],
       [ 0,  0,  0,  0,  0,  4,  2,  1,  8],
       [ 0,  0,  0,  0,  4,  2,  1,  8,  9],
       [ 0,  0,  0,  4,  2,  1,  8,  9, 10],
       [ 0,  0,  0,  0,  0,  0,  0, 11,  2],
       [ 0,  0,  0,  0,  0,  0, 11,  2,  1],
       [ 0,  0,  0,  0,  0, 11,  2,  1,  5],
       [ 0,  0,  0,  0, 11,  2,  1,  5, 12],
       [ 0,  0,  0, 11,  2,  1,  5, 12,  3],
       [ 0,  0, 11,  2,  1,  5, 12,  3,  4],
       [ 0, 11,  2,  1,  5, 12,  3,  4,  2],
       [ 0,  0,  0,  0,  0,  0,  0, 13, 14],
       [ 0,  0,  0,  0,  0,  0, 13, 14, 15],
       [ 0,  0,  0,  0,  0, 13, 14, 15,  1],
       [ 0,  0,  0,  0, 13, 14, 15,  1,  5],
       [ 0,  0,  0, 13, 14, 15,  1,  5, 16],
       [ 0,  0, 13, 14, 15,  1,  5, 16,  3],
       [ 0, 13, 14, 15,  1,  5, 16,  3,  6],
       [13, 14, 15,  1,  5, 16,  3,  6,  7],
       [ 0,  0,  0,  0,  0,  0,  0,  6,  7],
       [ 0,  0,  0,  0,  0,  0,  6,  7,  1],
       [ 0

In [ ]:
X=padded_input_sequences[:,:-1]

# we removed the last col

In [ ]:
Y=padded_input_sequences[:,-1]

In [ ]:
# now we have our dataset
# text generation task converted to supervised learning task
# supervised mei is this a regression task or a classification ?
# output is a number
# so is it a regression task?
# no since the data is discrete , not there for some values
# so we take this as a classification task for multi class classification
#  we will apply 1 hot encoding
# so hum output mei sirf 2 nhi bhejenge


# [0 1 0 0 0 0 0 0 0]
# This is the one hot encoding
# we will use the second word as output

# when 3 hoga
# [0 0 1 0 0 0 0 0 0]
# we are tranforming our output and using 1 hot encoded representation
# let us say we have a total of 3 words
# let us say the output is


x = padded_input_sequences [:,:-1]
y = padded_input_sequences[:,-1]
x.shape
y.shape






(26,)

In [ ]:
y.shape

(26,)

In [ ]:
x.shape

(26, 8)

In [ ]:
tokenizer.word_index

{'is': 1,
 'learning': 2,
 'of': 3,
 'machine': 4,
 'a': 5,
 'artificial': 6,
 'intelligence': 7,
 'fun': 8,
 'and': 9,
 'exciting': 10,
 'deep': 11,
 'subset': 12,
 'natural': 13,
 'language': 14,
 'processing': 15,
 'branch': 16,
 'the': 17,
 'future': 18,
 'technology': 19}

In [ ]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=20)


# when we do tokenizer.words_index
# it starts from 1
# but encoding also includes 0 so to include last word also we did this


In [ ]:
y.shape

# every output is a 283 long input sequence
# now we are ready with our training data


(26, 20)

The architecture for this
Finally for output we will have varuous layers

1. EMBEDDING LAYER
2.LSTM
3. DENSE LAYER

In [ ]:
from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import Embedding, LSTM, Dense

In [ ]:
model = Sequential()
# Explicitly define input_shape
model.add(Embedding(input_dim=20, output_dim=10, input_shape=(8,)))
model.add(LSTM(150))
model.add(Dense(20, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_10 (Embedding)             │ (None, 8, 10)               │             200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_10 (LSTM)                       │ (None, 150)                 │          96,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 20)                  │           3,020 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 99,820 (389.92 KB)

 Trainable params: 99,820 (389.92 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X,y,epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.0000e+00 - loss: 2.9947
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.1923 - loss: 2.9905
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.1923 - loss: 2.9861
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.1923 - loss: 2.9813
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - accuracy: 0.1923 - loss: 2.9759
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.1538 - loss: 2.9695
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.1538 - loss: 2.9620
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.1538 - loss: 2.9531
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.1538 - loss: 2.9422
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.1538 - loss: 2.9291
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - accuracy: 0.1538 - loss: 2.9129
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.15

In [ ]:
text = "learn"
# tokenize
token_text = tokenizer.texts_to_sequences([text])[0]
# pad the sequence
padded_token_text = pad_sequences([token_text], maxlen=9, padding='pre')
# get the prediction
prediction = model.predict(padded_token_text)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


In [ ]:
padded_token_text

array([[0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [ ]:
model.predict(padded_token_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


array([[1.62431462e-07, 1.79235980e-01, 4.02773589e-01, 3.67364646e-06,
        1.02680508e-06, 2.38932855e-03, 5.67926406e-07, 1.00013994e-01,
        1.05615575e-02, 3.89066001e-04, 5.64107131e-06, 7.87310626e-08,
        4.07036569e-05, 1.59623621e-08, 1.83794841e-01, 1.19181827e-01,
        9.51575475e-06, 1.58441195e-03, 1.27694939e-05, 1.26636769e-06]],
      dtype=float32)

In [ ]:
model.predict(padded_token_text).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


(1, 20)

In [ ]:
tokenizer.word_index

{'is': 1,
 'learning': 2,
 'of': 3,
 'machine': 4,
 'a': 5,
 'artificial': 6,
 'intelligence': 7,
 'fun': 8,
 'and': 9,
 'exciting': 10,
 'deep': 11,
 'subset': 12,
 'natural': 13,
 'language': 14,
 'processing': 15,
 'branch': 16,
 'the': 17,
 'future': 18,
 'technology': 19}

In [ ]:
import numpy as np
pos=np.argmax(model.predict(padded_token_text))
predicted_word = tokenizer.index_word.get(pos, "")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step


In [ ]:
def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_text = tokenizer.texts_to_sequences([text])[0]
    padded_token_text = pad_sequences([token_text], maxlen=max_sequence_len - 1, padding='pre')
    prediction = model.predict(padded_token_text, verbose=0)
    predicted_word_index = np.argmax(prediction)
    predicted_word = tokenizer.index_word.get(predicted_word_index, "")
    return predicted_word

# Step 7: Test the next word predictor
seed_text = "learn"
next_word = predict_next_word(model, tokenizer, seed_text, 9)
print(f"Seed text: {seed_text} -> Next word: {next_word}")

Seed text: learn -> Next word: learning
